services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  microservice-calculator:
    build:
      context: .
      dockerfile: ./apps/microservice-calculator/Dockerfile
    container_name: microservice-calculator
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    ports:
      - "3000:3000"

  parity:
    build:
      context: .
      dockerfile: ./apps/parity/Dockerfile
    container_name: parity
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    ports:
      - "3001:3001"

  prime:
    build:
      context: .
      dockerfile: ./apps/prime/Dockerfile
    container_name: prime
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    ports:
      - "3002:3002"

  factorial:
    build:
      context: .
      dockerfile: ./apps/factorial/Dockerfile
    container_name: factorial
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    ports:
      - "3003:3003"

  sum-n:
    build:
      context: .
      dockerfile: ./apps/sum-n/Dockerfile
    container_name: sum-n
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    ports:
      - "3004:3004"

  fibonacci:
    build:
      context: .
      dockerfile: ./apps/fibonacci/Dockerfile
    container_name: fibonacci
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    ports:
      - "3005:3005"
